### ISSUE TITLE
create_bat function: Conditional formatting sometimes formats the wrong rows

### ISSUE THREAD

**Issue by GitWray1** [vtwkam1/baseline-assessment-tool#2]
The create_BAT() function will sometimes apply the conditional formatting to the wrong rows. This is likely due to an issue in lines 258-260 of the create_BAT.R file. 

https://github.com/vtwkam1/baseline-assessment-tool/blob/96ec9136a66e966d10ccb230f9c21c3164c83e5a/R/create_BAT.R#L258-L260

**Comment by vtwkam1** [comment]
Note, selecting the specific rows with recs doesn't have the desired effect as the data validation has to be applied to "[contiguous rows](https://ycphs.github.io/openxlsx/reference/dataValidation.html)". So the headers, subheaders etc after row 5 will also have the drop down list.
